# syntax=docker/dockerfile:experimental
# BUILD IMAGE
FROM node:18

RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    libomniorb4-dev

WORKDIR /opt/quantel-gateway
COPY . .
RUN yarn install --check-files --frozen-lockfile

CMD ["yarn", "test"]
